namespace UniGame.Ecs.Bootstrap.Runtime.Config
{
#if UNITY_EDITOR
    
    using System;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using UnityEditor;
    using UnityEngine;

    public static class EcsLinkXmlGenerator
    {
        // Путь до link.xml
        public const string LinkXmlPath = "Assets/link.xml";

        // Маркеры авто-блока — содержимое между ними переписывается.
        private const string BeginMarker = "<!-- BEGIN-AUTO-GENERATED-BY-LinkXmlGenerator -->";
        private const string EndMarker = "<!-- END-AUTO-GENERATED-BY-LinkXmlGenerator -->";

        private static List<Type> _types = new List<Type>();
        
        public static void GenerateLinkXml(IEnumerable<Type> types)
        {
            _types.Clear();
            _types.AddRange(types);
            GenerateLinkXml(_types);
            _types.Clear();
        }

        /// <summary>
        /// Сгенерировать/обновить авто-секцию по переданному списку типов.
        /// </summary>
        public static void GenerateLinkXml(List<Type> types)
        {
            if (types == null) throw new ArgumentNullException(nameof(types));

            // Удаляем дубли и системные/открытые generic типы, сортируем.
            var clean = new HashSet<Type>(types
                    .Where(t => t != null && !t.IsGenericTypeDefinition) // открытые generic тут бесполезны
            );

            // Группируем по сборкам -> список полных имен типов
            var byAssembly = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
            foreach (var t in clean)
            {
                var asmName = t.Assembly.GetName().Name; // без версии/токена
                if (!byAssembly.TryGetValue(asmName, out var set))
                {
                    set = new SortedSet<string>(StringComparer.Ordinal);
                    byAssembly[asmName] = set;
                }

                // В link.xml для вложенных типов допустим формат Namespace.Outer+Inner
                var full = t.FullName ?? t.Name;
                set.Add(full);
            }

            // Формируем XML-фрагмент для авто-вставки
            var gen = new StringBuilder();
            gen.AppendLine(BeginMarker);
            gen.AppendLine("  <!-- DO NOT EDIT MANUALLY: this section is regenerated by LinkXmlGenerator -->");
            foreach (var kv in byAssembly)
            {
                gen.AppendLine($"  <assembly fullname=\"{Escape(kv.Key)}\" >");
                foreach (var typeName in kv.Value)
                {
                    gen.AppendLine($"    <type fullname=\"{Escape(typeName)}\" preserve=\"all\"/>");
                }

                gen.AppendLine("  </assembly>");
            }

            gen.AppendLine(EndMarker);

            // Обеспечиваем наличие базового файла link.xml с корнем <linker>...</linker>
            EnsureBaseLinkXml();

            // Читаем текущий файл и обновляем авто-блок
            var text = File.ReadAllText(LinkXmlPath, Encoding.UTF8);

            if (!text.Contains(BeginMarker) || !text.Contains(EndMarker))
            {
                // Вставляем наш блок перед закрывающим тегом </linker>
                int insertPos = text.LastIndexOf("</linker>", StringComparison.OrdinalIgnoreCase);
                if (insertPos < 0)
                    throw new InvalidOperationException("link.xml: root <linker> not found.");

                text = text.Insert(insertPos, "  " + gen.ToString() + Environment.NewLine);
            }
            else
            {
                // Заменяем содержимое между маркерами
                text = ReplaceBetween(text, BeginMarker, EndMarker, gen.ToString());
            }

            File.WriteAllText(LinkXmlPath, text, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            AssetDatabase.ImportAsset(LinkXmlPath);
            
            Debug.Log($"[LinkXmlGenerator] link.xml updated at: {LinkXmlPath}");
        }

        // Создать базовый link.xml если его нет, и гарантировать наличие корня и маркеров.
        private static void EnsureBaseLinkXml()
        {
            if (!File.Exists(LinkXmlPath))
            {
                var sb = new StringBuilder();
                sb.AppendLine("<linker>");
                sb.AppendLine("  <!-- You can keep your manual rules here -->");
                sb.AppendLine($"  {BeginMarker}");
                sb.AppendLine("  <!-- DO NOT EDIT MANUALLY: this section is regenerated by LinkXmlGenerator -->");
                sb.AppendLine($"  {EndMarker}");
                sb.AppendLine("</linker>");
                Directory.CreateDirectory(Path.GetDirectoryName(LinkXmlPath)!);
                File.WriteAllText(LinkXmlPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                AssetDatabase.ImportAsset(LinkXmlPath);
                return;
            }

            var text = File.ReadAllText(LinkXmlPath, Encoding.UTF8);
            if (!text.Contains("<linker>"))
                throw new InvalidOperationException("link.xml must have a <linker> root element.");

            // Если маркеров нет — добавим перед </linker>
            if (!text.Contains(BeginMarker) || !text.Contains(EndMarker))
            {
                int insertPos = text.LastIndexOf("</linker>", StringComparison.OrdinalIgnoreCase);
                if (insertPos < 0)
                    throw new InvalidOperationException("link.xml: root <linker> not found.");

                var block = new StringBuilder();
                block.AppendLine($"  {BeginMarker}");
                block.AppendLine("  <!-- DO NOT EDIT MANUALLY: this section is regenerated by LinkXmlGenerator -->");
                block.AppendLine($"  {EndMarker}");
                block.AppendLine();

                text = text.Insert(insertPos, block.ToString());
                File.WriteAllText(LinkXmlPath, text, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                AssetDatabase.ImportAsset(LinkXmlPath);
            }
        }

        private static string ReplaceBetween(string source, string begin, string end, string wholeReplacement)
        {
            int start = source.IndexOf(begin, StringComparison.Ordinal);
            int stop = source.IndexOf(end, StringComparison.Ordinal);
            if (start < 0 || stop < 0 || stop < start)
                return source; // не нашли — ничего не меняем

            // Вырезаем участок целиком (включая маркеры) и вставляем готовый блок
            var prefix = source.Substring(0, start);
            var suffix = source.Substring(stop + end.Length);
            // Добавим перевод строки если нужно
            if (!prefix.EndsWith("\n")) prefix += Environment.NewLine;
            if (!wholeReplacement.EndsWith("\n")) wholeReplacement += Environment.NewLine;
            return prefix + wholeReplacement + suffix;
        }

        private static string Escape(string s)
        {
            return s
                .Replace("&", "&amp;")
                .Replace("\"", "&quot;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }
    }
#endif
}